# Generated by Django 6.0.5 on 2026-07-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_attendance_qr_scanned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='myapp.complaint'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_workflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='myapp.loan'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='member_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='scheme_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='myapp.schemeapplication'),
        ),
    ]
